version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/clean-node-api
    environment:
      - PORT=5050
      - MONGO_URL=mongodb://mongo:27017/clean-typescript-api
      - JWT_SECRET_KEY=secret_key
    restart: always
    command: bash -c "npm install --omit=dev && npm install nodemon && npm start"
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
    links: 
      - mongo